"""init schema

Revision ID: 0862e5374be8
Revises:
Create Date: 2026-04-17 15:55:58.061641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0862e5374be8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_tag_category"), "tag", ["category"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("wechat", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("industry", sa.String(length=64), nullable=True),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column("education_level", sa.String(length=16), nullable=True),
        sa.Column("job_status", sa.String(length=16), nullable=False),
        sa.Column("current_salary_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("current_salary_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("expected_salary_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("expected_salary_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("skills", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("derived_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resume_quality", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resume_quality_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column("resume_file_id", sa.Integer(), nullable=True),
        sa.Column("raw_extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candidate_city"), "candidate", ["city"], unique=False)
    op.create_index(op.f("ix_candidate_email"), "candidate", ["email"], unique=False)
    op.create_index(op.f("ix_candidate_industry"), "candidate", ["industry"], unique=False)
    op.create_index(op.f("ix_candidate_is_deleted"), "candidate", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_candidate_owner_id"), "candidate", ["owner_id"], unique=False)
    op.create_index(op.f("ix_candidate_phone"), "candidate", ["phone"], unique=False)
    op.create_table(
        "candidate_education",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("school", sa.String(length=128), nullable=False),
        sa.Column("degree", sa.String(length=16), nullable=True),
        sa.Column("major", sa.String(length=64), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_education_candidate_id"),
        "candidate_education",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "candidate_experience",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("company_name", sa.String(length=128), nullable=False),
        sa.Column("position_title", sa.String(length=128), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_experience_candidate_id"),
        "candidate_experience",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "candidate_project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tech_stack", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_project_candidate_id"),
        "candidate_project",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "candidate_tag",
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("candidate_id", "tag_id"),
    )
    op.create_index(op.f("ix_candidate_tag_tag_id"), "candidate_tag", ["tag_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidate_tag_tag_id"), table_name="candidate_tag")
    op.drop_table("candidate_tag")
    op.drop_index(op.f("ix_candidate_project_candidate_id"), table_name="candidate_project")
    op.drop_table("candidate_project")
    op.drop_index(op.f("ix_candidate_experience_candidate_id"), table_name="candidate_experience")
    op.drop_table("candidate_experience")
    op.drop_index(op.f("ix_candidate_education_candidate_id"), table_name="candidate_education")
    op.drop_table("candidate_education")
    op.drop_index(op.f("ix_candidate_phone"), table_name="candidate")
    op.drop_index(op.f("ix_candidate_owner_id"), table_name="candidate")
    op.drop_index(op.f("ix_candidate_is_deleted"), table_name="candidate")
    op.drop_index(op.f("ix_candidate_industry"), table_name="candidate")
    op.drop_index(op.f("ix_candidate_email"), table_name="candidate")
    op.drop_index(op.f("ix_candidate_city"), table_name="candidate")
    op.drop_table("candidate")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_tag_category"), table_name="tag")
    op.drop_table("tag")
    op.drop_table("role")
    # ### end Alembic commands ###
