"""add attachment + resume_task

Revision ID: 71666f29944c
Revises: 0862e5374be8
Create Date: 2026-04-17 16:08:05.060996

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "71666f29944c"
down_revision: str | None = "0862e5374be8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uploader_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("mime", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("owner_type", sa.String(length=32), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attachment_owner_id"), "attachment", ["owner_id"], unique=False)
    op.create_index(op.f("ix_attachment_owner_type"), "attachment", ["owner_type"], unique=False)
    op.create_index(op.f("ix_attachment_sha256"), "attachment", ["sha256"], unique=False)
    op.create_index(op.f("ix_attachment_uploader_id"), "attachment", ["uploader_id"], unique=False)
    op.create_table(
        "resume_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("derived_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resume_quality", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["attachment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_task_candidate_id"), "resume_task", ["candidate_id"], unique=False
    )
    op.create_index(op.f("ix_resume_task_status"), "resume_task", ["status"], unique=False)
    op.create_index(op.f("ix_resume_task_user_id"), "resume_task", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resume_task_user_id"), table_name="resume_task")
    op.drop_index(op.f("ix_resume_task_status"), table_name="resume_task")
    op.drop_index(op.f("ix_resume_task_candidate_id"), table_name="resume_task")
    op.drop_table("resume_task")
    op.drop_index(op.f("ix_attachment_uploader_id"), table_name="attachment")
    op.drop_index(op.f("ix_attachment_sha256"), table_name="attachment")
    op.drop_index(op.f("ix_attachment_owner_type"), table_name="attachment")
    op.drop_index(op.f("ix_attachment_owner_id"), table_name="attachment")
    op.drop_table("attachment")
    # ### end Alembic commands ###
