"""add company + position

Revision ID: 8e5bd01fe8d0
Revises: 71666f29944c
Create Date: 2026-04-17 16:27:29.941087

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "8e5bd01fe8d0"
down_revision: str | None = "71666f29944c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("industry_tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("scale", sa.String(length=16), nullable=True),
        sa.Column("funding_stage", sa.String(length=16), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("contact_name", sa.String(length=64), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("cooperation_status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_is_archived"), "company", ["is_archived"], unique=False)
    op.create_index(op.f("ix_company_name"), "company", ["name"], unique=False)
    op.create_index(op.f("ix_company_owner_id"), "company", ["owner_id"], unique=False)
    op.create_table(
        "position",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=True),
        sa.Column("responsibilities", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("required_skills", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("nice_to_have_skills", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("required_capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("min_years", sa.Integer(), nullable=True),
        sa.Column("max_years", sa.Integer(), nullable=True),
        sa.Column("required_education", sa.String(length=16), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("remote_ok", sa.Boolean(), nullable=False),
        sa.Column("headcount", sa.Integer(), nullable=False),
        sa.Column("benefits", sa.Text(), nullable=True),
        sa.Column("onboard_deadline", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("closed_reason", sa.String(length=255), nullable=True),
        sa.Column("is_template", sa.Boolean(), nullable=False),
        sa.Column("template_name", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_position_city"), "position", ["city"], unique=False)
    op.create_index(op.f("ix_position_company_id"), "position", ["company_id"], unique=False)
    op.create_index(op.f("ix_position_owner_id"), "position", ["owner_id"], unique=False)
    op.create_index(op.f("ix_position_status"), "position", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_position_status"), table_name="position")
    op.drop_index(op.f("ix_position_owner_id"), table_name="position")
    op.drop_index(op.f("ix_position_company_id"), table_name="position")
    op.drop_index(op.f("ix_position_city"), table_name="position")
    op.drop_table("position")
    op.drop_index(op.f("ix_company_owner_id"), table_name="company")
    op.drop_index(op.f("ix_company_name"), table_name="company")
    op.drop_index(op.f("ix_company_is_archived"), table_name="company")
    op.drop_table("company")
    # ### end Alembic commands ###
